---
title: "Data Processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Libaraies needed:

```{r}
library(tidyverse)
library(skimr)
library(randomForest)
```

## Read in data
```{r}
dat <- read_csv("data/train.csv")
skim(dat)
```

## Change data class
```{r}
glimpse(dat)

dat <- dat %>%
    mutate_if(is.character, as.factor) %>%
    mutate(Id = as.factor(Id),
           MSSubClass = as.factor(MSSubClass),
           Alley = as.factor(replace_na(as.character(Alley), "No")),
           ExterQual = recode(ExterQual, "Ex" = 5, "Gd" = 4,"TA" = 3,"Fa" = 2,"Po" = 1),
           ExterCond = recode(ExterCond, "Ex" = 5, "Gd" = 4,"TA" = 3,"Fa" = 2,"Po" = 1),
           BsmtQual = as.factor(replace_na(as.character(BsmtQual), "NoBsmt")),
           BsmtCond = as.factor(replace_na(as.character(BsmtCond), "NoBsmt")),
           BsmtExposure = as.factor(replace_na(as.character(BsmtExposure), "NoBsmt")),
           BsmtFinType1 = as.factor(replace_na(as.character(BsmtFinType1), "NoBsmt")),
           BsmtFinType2 = as.factor(replace_na(as.character(BsmtFinType2), "NoBsmt")),
           HeatingQC = recode(HeatingQC , "Ex" = 5, "Gd" = 4,"TA" = 3,"Fa" = 2,"Po" = 1),
           KitchenQual = recode(KitchenQual, "Ex" = 5, "Gd" = 4,"TA" = 3,"Fa" = 2,"Po" = 1),
           Functional = recode(Functional, "Typ" = 8, "Min1" = 7,"Min2" = 6,"Mod" = 5,
                               "Maj1" = 4, "Maj2" = 3, "Sev" = 2, "Sal" = 1),
           FireplaceQu = as.factor(replace_na(as.character(FireplaceQu), "No")),
           GarageType = as.factor(replace_na(as.character(GarageType), "No")),
           GarageFinish = as.factor(replace_na(as.character(GarageFinish), "No")),
           GarageQual = as.factor(replace_na(as.character(GarageQual), "No")),
           GarageCond = as.factor(replace_na(as.character(GarageCond), "No")),
           PoolQC = as.factor(replace_na(as.character(PoolQC), "No")),
           Fence = as.factor(replace_na(as.character(Fence), "No")),
           MiscFeature = as.factor(replace_na(as.character(MiscFeature), "None")),
           )
           
glimpse(dat)

skim(dat)
```

## Missing data?

```{r}
dat %>% filter(is.na(MasVnrType) | MasVnrType == "None") %>% head() # True missing data

dat %>% select(LotFrontage) %>% head() # True missing data

dat %>% select(MasVnrType, MasVnrArea) %>%
    filter(is.na(MasVnrType)) # True missing data
```

## Imputation - Random Forest

```{r}
dat <- dat %>% select(-Id)
glimpse(dat)
```

```{r, eval=FALSE}
set.seed(100)
house <- rfImpute(SalePrice ~ ., dat)

save(house, file ="imputed.rda")
```

## Random forest

```{r}
load("imputed.rda")

head(house)

dim(house)

set.seed(100)
house$HighPrice <- ifelse(house$SalePrice >= 180000, 1, 0)
dat.train <- house[train<-sample(1:nrow(house), floor(nrow(house)*0.7)),]
dat.test <- house[-train,]
```

```{r, eval=FALSE}
set.seed(100)
tune_rf <- tuneRF(x = house[,2:80], y = house[,1], ntreeTry = 500)
tune_rf
tune_rf[which.min(tune_rf[,2]),1]
```

```{r}
m <- 26
set.seed(100)
rf_m <- randomForest(x = house[,2:80], y = house[,1], mtry = m, ntree = 1000,
                     keep.forest = TRUE)
plot(rf_m)
varImpPlot(rf_m, cex = 0.6)
```

## CART

```{r}
library(rpart)
library(rpart.plot)

# Set HighPrice
house1  <- dat.train[2:81]
# Build the tree
tree <- rpart(HighPrice ~ ., data = house1, method = "class",  
              control = rpart.control(minsplit = 10, cp = 0.001))
prp(tree, cex = 0.4, extra = 0)
plotcp(tree)
tree$variable.importance

# Prune the tree
bestcp <- tree$cptable[which.min(tree$cptable[, "xerror"]), "CP"]
tree.pruned <- prune(tree, cp = bestcp)
prp(tree.pruned, faclen = 0, cex = 0.8, extra = 1)
plotcp(tree.pruned)
tree.pruned$variable.importance

# Generate predicted values
tree.yhat <- predict(tree.pruned, newdata = dat.test, type = "class")

# Compute the residuals
res.tree.test <- (as.integer(dat.test$HighPrice) - 1) - (as.integer(tree.yhat) - 1)
mse.tree.test <- sum(res.tree.test^2)/length(res.tree.test)
mse.tree.test
```


